algoritmo "semnome"
// Função :
// Autor :
// Data : 14/03/2024
// Seção de Declarações 
var
n1,n2,soma,mult,divi,subi:real
inicio
// entrada
escreval("digite um numero")
leia(n1)
escreval("digite um numero")
leia(n2)

//processamento
soma<-n1+n2
subi<-n1-n2
mult<-n1*n2
divi<-n1/n2

//saida
escreval("esses são os resultados")
escreval("soma: " , soma ," divisão: "divi)
escreva("multiplicação: ", mult," subitração: ",subi)


fimalgoritmo
