algoritmo "semnome"
// Função :
// Autor :
// Data : 14/03/2024
// Seção de Declarações 
var
n1,n2,n3,n4,final:real
inicio
//entrada
escreval("insira a nota do 1 bimestre:")
leia(n1)
escreval("insira a nota do 2 bimestre:")
leia(n2)
escreval("insira a nota do 3 bimestre:")
leia(n3)
escreval("insira a nota do 4 bimestre:")
leia(n4)

//processamento
final<-(n1+n2+n3+n4)/4


//saida
escreval("essa é a nota final:",final)
fimalgoritmo
