algoritmo "semnome"
// Função :
// Autor :
// Data : 13/03/2024
// Seção de Declarações 
var
a,b,troca:real

inicio
// entradas
escreval("digite um valor para ser trocado:")
leia(a)
escreval("digite outro valor para ser trocado")
leia(b)
escreval("os valores são:")
escreval("A=",a, "B=",b)
escreval
//procassamento
troca<- a
a<- b
b<-troca

//saida
escreval("os valores trocados agora são:")
escreval("A=",a,"B=",b)



fimalgoritmo
