algoritmo "semnome"
// Função :
// Autor :
// Data : 14/03/2024
// Seção de Declarações 
var
nome:caracter
sala,vend,salf:real
inicio
//entrada
escreval("digite seu nome:")
leia(nome)
escreval("digite seu salario fixo:")
leia(sala)
escreval("digite total de vendas em dinheiro:")
leia(vend)

//processamento
salf<- vend*15/100+ sala

//saida
escreval("nome: ",nome, " salario fixo: ",sala, " salario final do mês: ",salf)



fimalgoritmo
